# Generated by Django 3.2.19 on 2023-06-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.CharField(max_length=32, unique=True)),
                ('book_name', models.CharField(max_length=32)),
            ],
        ),
    ]
